version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - "8000:80"
    volumes:
      - .:/project
    environment:
      - C_FORCE_ROOT=true
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      - redis
      - celery_worker

  celery_worker:
    build:
      context: .
      dockerfile: Dockerfile.backend
    command: celery -A backend.core.celery_worker worker --loglevel=info
    environment:
      - C_FORCE_ROOT=true
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    volumes:
      - .:/project
    depends_on:
      - redis

  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "9002:9000"
    environment:
      - API_URL=http://backend:80/api
    depends_on:
      - backend

networks:
  default:
    driver: bridge
