POST http://127.0.0.1:8080/login HTTP/1.1
Host: localhost:8080
Content-Type: application/json

{"username": "admin", "password": "dwqdqwgod"}


###
#{
#    "access_token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im15dXNlciJ9.Zrx3Ylq_RIRsSE2Ww8lWxROpeNZ8SbjOkUG1XKcCvQk"
#}



#{
#  "access_token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFkbWluIn0.ii0qaZGFZjfqgVp-iff3sUVPcZn1n24TzWyvLbTJYrI"
#}

###
GET  http://127.0.0.1:8080/items HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFkbWluIn0.ii0qaZGFZjfqgVp-iff3sUVPcZn1n24TzWyvLbTJYrI
